builds:
  - id: aws-sqs-filter-redrive
    main: main.go
    binary: aws-sqs-filter-redrive
    goos: [ windows, darwin, linux, freebsd, openbsd ]
    goarch: [ amd64, arm, arm64 ]
    goarm: [ 6, 7 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
archives:
  - id: aws-sqs-filter-redrive
    builds: [ aws-sqs-filter-redrive ]
    format: tar.gz
    files:
      - README.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: natenho
    name: aws-sqs-filter-redrive
  prerelease: auto
  disable: false
